### ISSUE TITLE
Instructions inaccurate for Boost 1.60

### ISSUE THREAD

**Issue by Vultraz** [aquileia/external#1]
If you use the source folder generated by the file command when building boost 1.60, you will get missing file errors when building.

**Comment by aquileia** [comment]
There are in fact two problems:
- boost needs absolute paths to zlib and bzip, therefore `../` has to be replaced in the b2 command.
- boost 1.60 broke MSVC compilation **again**, this time in `boost/type_traits/common_type.hpp` line 42 which was added in https://github.com/boostorg/type_traits/commit/9fd4ee06b2

I'll address the first issue, the second now has a ticket in their issue tracker:
https://svn.boost.org/trac/boost/ticket/11885

**Comment by Vultraz** [comment]
I still get these errors using the new command building in Codeblocks (boost was build with --toolset-gcc):

`C:\Users\Charles\Documents\wesnoth-git\src\ai\composite\aspect.hpp|31|fatal error: boost/pointer_cast.hpp: No such file or directory|
C:\Users\Charles\Documents\wesnoth-git\src\seed_rng.cpp|42|fatal error: boost/nondet_random.hpp: No such file or directory|
C:\Users\Charles\Documents\wesnoth-git\src\unit_filter.cpp|43|fatal error: boost/utility/in_place_factory.hpp: No such file or directory|
C:\Users\Charles\Documents\wesnoth-git\projectfiles\CodeBlocks\cb\include_tdm_gcc\boost\utility\in_place_factory.hpp|16|fatal error: boost/utility/detail/in_place_factory_prefix.hpp: No such file or directory|
C:\Users\Charles\Documents\wesnoth-git\projectfiles\CodeBlocks\cb\include_tdm_gcc\boost\utility\in_place_factory.hpp|28|fatal error: boost/utility/detail/in_place_factory_suffix.hpp: No such file or directory|
`

And of course, I still get these, but I cannot for the life of me figure out the cause:

`.objs-release\src\addon\client.o:client.cpp|| undefined reference to 'boost::system::system_category()'|
`
