### ISSUE TITLE
Missing OpenSSL headers

### ISSUE THREAD

**Issue by GregoryLundberg** [aquileia/external#22]
Specific need is openssl/rand.h

But why do we not have all of them? Picking a choosing bits and pieces of an upstream package does not seem wise.

**Comment by Wedge009** [comment]
I don't know - it looks like @CelticMinstrel added them originally. I'm also concerned that Wesnoth reads the headers as 1.1.0f (g is current as of November 2017) while the binary run-time is 0.9.8o which is declared 'should not be used'.

**Comment by CelticMinstrel** [comment]
I just uploaded the version I had available without really looking at the version. Obviously both I and this repo should be updated if the version is that old.

**Comment by GregoryLundberg** [comment]
0.9.8 is scary old
luckily, at this point we only use RC4 and nothing else.
I'm adding using the RNG.
And I'm planning on eliminating RC4 but there's some push-back about that so I may not

So OpenSSL is __*way*__ overkill. But it's convenient.

An alternative would be to drop OpenSSL entirely and import RC4 and a crypto-safe RNG directly into the source tree for Wesnoth.

**Comment by CelticMinstrel** [comment]
I thought we also used MD5? Or was that code removed with the switch to bcrypt?

I'm not really a fan of importing crypto code into the repository as was done with bcrypt. Yes OpenSSL/libcrypto is overkill, but it does do the job.

As for dropping RC4, it would need to be done before 1.14 and be replaced with some other symmetric cipher. But If I recall correctly it's what I used for encrypting your saved passwords (and isn't used anywhere else) so I don't think improving the cipher is worthwhile. I'd say just keep it, in other words.

**Comment by GregoryLundberg** [comment]
Oh, yeah, forgot MD5.

The problem with bcrypt is there is no other option, especially if we want to ensure compatibility with PHP.

i have a real problem with storing passwords in plain text, or even in a plain-text equivalent such as RC4. But there seems to be a real push-back against properly protecting the player's Forum password and time is short. So I'm probably going to join the ostriches and pray nobody complains that their Forum account was hijacked because we didn't do our jobs properly.

Same for replacing the lame-ass, insecure, easily hacked MD5 password hashing for add-ons. At least, there, it's just a UMC author complaining his content was hijacked and the admins can fix it by a laying on of hands.

**Comment by CelticMinstrel** [comment]
Seemingly we're also using SHA1, though I don't remember what for.

**Comment by Wedge009** [comment]
I don't profess to know anything about SSL implementations or much else about security in general, but I tried building openssl previously when it was first introduced into Wesnoth, gave up, and just used what celmin uploaded.

Doing some reading - and being well aware that a lot of stuff written is subjective opinion - a surface glance suggests that libressl might be suitable by virtue of being less bloated than openssl (I understand it's stripped down - or is at least in the process of doing so - a lot of the relatively unused excess that can make openssl insecure).

With respect to the above commentary that openssl in Wesnoth is overkill, could/should we try using libressl instead?

**Comment by CelticMinstrel** [comment]
Well, if MD5 is considered part of the excess (which it could well be, given that it's not a secure hash), then switching over seems like it could be a problem...

**Comment by Wedge009** [comment]
I apologise for my previous remarks about the DLL celmin uploaded being old - turns out Wesnoth had picked up the ancient 0.9.8 DLL from my C:\Windows directory. No idea what installed it there - a search of my system drive brings up several other libeay32.dll files of varying versions from 1.0.0 series to 1.1.x.

Anyway, after some effort I managed to build WIN32 libraries for the current 1.1.0g. But it turns out that the default file names have changed from libeay32 to libcrypto and ssleay32 to libssl respectively. So I'm not updating the external repository because the file name changes would undoubtedly break various IDE projects - it certainly breaks VS. I can't remember if celmin built the openssl libraries himself or uploaded a copy from someone/somewhere else.

On the other hand, I do note only libcrypto (libeay32) is used/necessary. I take it we're not actually using SSL in Wesnoth, just the cryptographic functions it's based on.

**Comment by GregoryLundberg** [comment]
1) Bite the bullet and use the new names if for no other reason than to avoid panicking those of us old enough to remember the pain and angst of dealing with the politics of SSLeay.

2) Since OpenSSL does not officially supply binaries, so building from source is probably wise. You could get pre-built binaries, though, if there are any trusted sources for those. (Although while, for me, any sentence with both "trusted" and "Windows" is probably an oxymoron, I usually just cross my fingers and snag a pre-built rather than going through the pain of doing it myself.)

3) 1.1.0g is good.

4) Yes, we only use the RNG, SHA1, MD5, and RC4 but install the full package so if we need something else (or get smart and secure some communications) we won't have this surprise again.

**Comment by CelticMinstrel** [comment]
1. I got pre-built binaries from somewhere, don't remember where. I thought someone else already replaced the version I uploaded though?

2. I don't mind including all the libcrypto headers but I'd prefer not to include all of OpenSSL. We only need crypto after all.

**Comment by Wedge009** [comment]
@GregoryLundberg 
1. I might be old enough to qualify, but I wasn't around in the software development world at the time. From what I read, it seems the individual EAY wrote this SSL implementation which eventually became the OpenSSL project though the libraries were renamed as part of 1.1.x series (although I note that the 1.1.0f release that CelMin uploaded managed to keep the original libeay32.dll naming - maybe the compiler set it up that way for backwards-compatibility).

2. Yes, and it makes sense for them not to do this, especially considering the sensitive nature of the library. And yes, I know Windows isn't exactly a trustworthy platform, but then neither should any other closed-sourced platform. I understand the convenience aspect. If you're willing to trust my compilation, I'm happy to update the external repository for Wesnoth. (I quite literally only downloaded 1.1.0g source code, the latest x86 ActivePerl release for Windows 5.22.4.2205 - don't know if it's still maintained as things move to 64-bit - and NASM 2.13.03, and somehow combined them all to nmake the OpenSSL packages.)

3. Yes, current stable release as of time of writing.

4. Yes, saw all these functions being used before OpenSSL dependencies were satisfied in Wesnoth compilation. If we're using a lot of cryptography, it makes sense to me to use a dedicated library for it and this seems like a good option even if it could be considered 'overkill'.

@CelticMinstrel 
1. As best as I can tell from the commit history (at least for VC15 branch), you uploaded the original headers and binaries, @jyrkive just added some missing headers and moved them to locations as per OpenSSL convention.

2. I don't see any issue with adding all the headers that the build produced (there are 76). It also makes sense to only include libcrypto, though really the only other binary is libssl.

**Comment by GregoryLundberg** [comment]
I'd prefer all the headers, and all dll for dynamic linking. We should not statically link against OpenSSL so if a security patch comes out we can bump letter-release without recompiling or relinking. The fact we don't presently use the TLS stuff does not mean we won't. So let's prevent future surprises.

**Comment by Wedge009** [comment]
I don't disagree with that view either.

So the only question really is whether or not the name change is acceptable. If so, I'll make the update.

**Comment by CelticMinstrel** [comment]
I couldn't care less about what the library is actually called. So in my opinion, go ahead and change it.

**Comment by Wedge009** [comment]
I will update the corresponding MSVC project files, then, and expect other projects will be updated accordingly.

**Comment by CelticMinstrel** [comment]
The Xcode project, scons, and CMake all reference it as libcrypto if I recall correctly, so it should be only MSVC projects that need updating.

**Comment by Wedge009** [comment]
Wow, okay, cool.

Edit: Of course, I just realised that it's only really Windows build that relies on this repository.

**Comment by Wedge009** [comment]
'tis done. Please let me know if you have any problems with the update or if we can close this.

**Comment by Vultraz** [comment]
Should this not be closed?
