### ISSUE TITLE
Boost missing parts

### ISSUE THREAD

**Issue by GregoryLundberg** [aquileia/external#4]
C:\projects\wesnoth\src\spirit_po/default_plural_forms_expressions.hpp(25): fatal error C1083: Cannot open include file: 'boost/spirit/include/qi.hpp': No such file or directory

At present this issue only prevents using the pre-builts for 1.13.6+dev. Building updated Boost is not an option as it exceeds the run-time limit for the MSVC CI system; which depends upon the VC12 download from this project.

**Comment by aquileia** [comment]
Fixed by adding the Boost spirit library + dependencies
