### ISSUE TITLE
Add Visual Studio 2017 support

### ISSUE THREAD

**Issue by GregoryLundberg** [aquileia/external#5]
Released today, 7MAR2017, free Community Edition is available for download.

**Comment by Wedge009** [comment]
I did the 'off-line installer' download thinking that it would be ISO-sized of the order of maybe 10 GiB at most. It was a 24 GiB download. Thanks a bunch, Microsoft, not everyone in the world has infinite downloads. D:

Haven't installed it yet. Might have to wait till I get my larger system drive installed - running out of space on the current one.

**Comment by GregoryLundberg** [comment]
Yeah, it would be nice if they'd say, first, the size of the ISO in a more prominent way.

When you fire it up you'll realize there is a LOT of junk in that ISO you won't need: SQL Server,   Azure Cloud, Android, iOS, Javascript, Typescript, 4 (!) versions of Windows 10 SDK.

I had a 1T drive and unlimited data so I said "what the heck" .. 24GB is the download size. It will take about 100GB when installed.

**Comment by Wedge009** [comment]
Looks like updates are only done through the on-line installer now - as soon as I installed it there was an update to be downloaded (bumping the version from 26228.0 to 26228.9). Such is the way of the American world, I suppose.

Fortunately I didn't need 100GB, I only install the basics that I use - 'classic' Windows development using C++ so my installation is much the same as 2015, about 6 or 7 GiB.

Anyway, I have Wesnoth running fine on 2017. It seems quite similar to 2015, so thankfully no breaking changes (that I've found so far). I was surprised that I didn't need to rebuild boost (the tool-kit says it only went from v140 to v141) - I'll probably do a build for 2017 when the next boost version is released.

**Comment by Wedge009** [comment]
I'm not sure how @aquileia wants this structured but I created VC15 branch from current VC14 head (I hope this is the right convention as VS2017 is 15.0 internally but VC is only 14.1), replaced boost 1.62 libraries and headers with 1.64.

I just went by https://github.com/aquileia/external/blob/master/README.md - I notice it doesn't yet specify the phoenix, spirit, and fusion modules that people were requesting previously. Not sure if those should be updated too.

**Comment by GregoryLundberg** [comment]
I locally cloned the project and checked out the VS15 branch. The project builds with no errors, two warnings, and an unexpected new directory. Wesnoth PR 1732 corrects those issues. Light testing showed no issues.

**Comment by Wedge009** [comment]
Microsoft is updating VS2017 every few weeks or so and even the recently released boost 1.65 won't recognise the latest compiler version. As far as I know, there's no harm in increasing the maximum VC version at https://github.com/aquileia/external/blob/VC15/include/boost/config/compiler/visualc.hpp#L320, with the proviso that the user recognise that newer compilers might not necessarily be supported of course.

**Comment by Wedge009** [comment]
boost 1.65.1 release seems to accommodate VS2017.3
